services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
      POSTGRES_DB: portfolio
    ports: ["5432:5432"]
    volumes: [db:/var/lib/postgresql/data]
volumes: { db: {} }
